# App settings
BASE_URL = "INSERT HEROKU BASE URL"
PLIVO_NUMBER = "INSERT PLIVO NUMBER"

# Plivo tokens
PLIVO_AUTH_ID = "INSERT PLIVO AUTH ID"
PLIVO_AUTH_TOKEN = "INSERT PLIVO AUTH TOKEN"

# Pusher tokens from heroku
PUSHER_APP_ID = ""
PUSHER_KEY = ""
PUSHER_SECRET = ""
